site_name: PhotonCSS Documentation

theme:
  name: material
  font:
    text: Roboto
    code: Fira Code
  logo: assets/icon.png

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true

repo_url: https://github.com/PhotonCSS/Photon/tree/gamma
edit_uri: https://github.com/PhotonCSS/PhotonDocs/edit/master/docs/
copyright: Copyright &copy; 2018 - 2021 Josh Merlino
